version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: subscriptions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/subscriptions?sslmode=disable
      DEBUG: "true"
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data: {}


